### ISSUE TITLE
Unable to load asset: packages/intl_phone_number_input/assets/flags/pk.png

### ISSUE THREAD

**Issue by AliYar-Khan** [natintosh/intl_phone_number_input#214]
I assign intial country as 'PK' for Pakistan and for phone number isoCode 'PK' but it failed to loads the asset image of Pakistan flag with this exception

When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:227:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:667:14)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "packages/intl_phone_number_input/assets/flags/pk.png")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#be7ef(), name: "packages/intl_phone_number_input/assets/flags/pk.png", scale: 1.0)

I am using intl_phone_number_input: ^0.7.0+2 version of this package

Flutter sdk version is 2.0.5

Reproduce it: 

```

String initialCountry = 'PK';
PhoneNumber number = PhoneNumber(isoCode: 'PK');

InternationalPhoneNumberInput(
                                              onInputChanged:
                                                  (PhoneNumber number) {
                                                print(number.phoneNumber);
                                              },
                                              onInputValidated: (bool value) {
                                                print(value);
                                              },
                                              selectorConfig: SelectorConfig(
                                                selectorType:
                                                    PhoneInputSelectorType
                                                        .BOTTOM_SHEET,
                                              ),
                                              ignoreBlank: false,
                                              autoValidateMode:
                                                  AutovalidateMode.disabled,
                                              selectorTextStyle: TextStyle(
                                                  color: Colors.black),
                                              initialValue: number,
                                              textFieldController: controller,
                                              formatInput: false,
                                              keyboardType: TextInputType
                                                  .numberWithOptions(
                                                      signed: true,
                                                      decimal: true),
                                              // inputBorder: OutlineInputBorder(),
                                              inputDecoration: InputDecoration(
                                                contentPadding:
                                                    EdgeInsets.all(10),
                                                enabled: true,
                                              ),
                                              onSaved: (PhoneNumber number) {
                                                print('On Saved: $number');
                                              },
                                            )
                                            
```
                                            
**Expected behavior**
Should display Pakistan flag with country code

**Screenshots**
![Screenshot_1619891634](https://user-images.githubusercontent.com/37889962/116790872-25db9880-aad0-11eb-8818-0bf9b2ffa429.png)

** Targeted platforms (please complete the following information):**
Android

**Comment by natintosh** [comment]
try `flutter clean` and re-run the project
