### ISSUE TITLE
Can't validate the phone

### ISSUE THREAD

**Issue by lecuivre-alban** [natintosh/intl_phone_number_input#61]
**The bug**
Exception thrown when editing the phone and can't validate.

**Package version**
`0.4.5`

**Flutter version / Flutter doctor**
```
$ flutter doctor -v
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.5 19F101, locale fr-FR)
    • Flutter version 1.18.0-11.1.pre at ...
    • Framework revision 2738a1148b (4 weeks ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)
[✓] ...
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4
[✓] ...
[✓] ...
[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0
[✓] ...
• No issues found!
```

**My code**
```dart
        InternationalPhoneNumberInput(
          textFieldController: phoneCtrl,
          keyboardAction: TextInputAction.next,
          countries: ['FR'],
          initialValue: PhoneNumber(isoCode: 'FR'),
          inputDecoration: InputDecoration(
            labelText: 'Numéro de téléphone'
          ),
          errorMessage: 'Numéro de téléphone non valide',
          onInputChanged: (PhoneNumber value) { 
            // code 
          }, // EDIT
        ),
```
**Errors**
- First one, triggered whenever I change the value in the field
```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      _InputWidgetState.phoneNumberControllerListener.<anonymous closure> 
package:intl_phone_number_input/…/widgets/input_widget.dart:308
#1      _rootRunUnary  (dart:async/zone.dart:1192:38)
#2      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
#3      _FutureListener.handleValue  (dart:async/future_impl.dart:141:18)
#4      Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:686:45)
#5      Future._propagateToListeners  (dart:async/future_impl.dart:715:32)
#6      Future._completeWithValue  (dart:async/future_impl.dart:526:5)
#7      _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:36:15)
#8      _completeOnAsyncReturn  (dart:async-patch/async_patch.dart:303:13)
#9      _InputWidgetState.getParsedPhoneNumber (package:intl_phone_number_input/src/widgets/input_widget.dart)
<asynchronous suspension>
#10 <…>
```
- Second one, I'm always getting the error message when validating the field

**Platforms**
 - Developing on MacOS
 - Debugging on iOS simulator

**Comment by natintosh** [comment]
Hi @lecuivre-alban thanks for raising this, it seems you did add the `onInputChanged` property to the widget. For instance,

```dart
InternationalPhoneNumberInput(
  textFieldController: phoneCtrl,
  keyboardAction: TextInputAction.next,
  countries: ['FR'],
  initialValue: PhoneNumber(isoCode: 'FR'),
  inputDecoration: InputDecoration(
    labelText: 'Numéro de téléphone'
  ),
  errorMessage: 'Numéro de téléphone non valide',
  onInputChanged: (PhoneNumber value) {},
),
```

But I'll definitely publish a hotfix to prevent such exception this week

**Comment by lecuivre-alban** [comment]
Oh yes, sorry I forgot to copy this property.
Anyway, thank you for your quick feedback.
And I forgot to say it before but good job ! Bugs aside, your package is awesome 😉
